### ISSUE TITLE
hsakmt-roct fails to build

### ISSUE THREAD

**Issue by SirRujak** [ROCm/rocm-spack-pkgs#11]
When attempting to build rocm-opencl using `spack install -j4 rocm-opencl %gcc@8.3.0` I have been running into some issues. The first is that hsakmt-roct complains about libnuma missing, the error can be found below. I decided to use gcc@8.3.0 since it was most similar to the 8.3.1 I found CentOS to be using currently. I am on Solus which is currently at 9.3.0 which has the same effect. Any assistance would be appreciated!

<details>
  <summary> libnuma error</summary>

> 
> Error: ProcessError: Command exited with status 2:
>     'make' '-j4'
> 
> 3 errors found in build log:
>      47    [ 18%] Building C object CMakeFiles/hsakmt.dir/src/fmm.c.o
>      48    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/fmm.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/fmm.c
>      49    [ 25%] Building C object CMakeFiles/hsakmt.dir/src/events.c.o
>      50    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/events.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/events.c
>      51    [ 31%] Building C object CMakeFiles/hsakmt.dir/src/libhsakmt.c.o
>      52    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/libhsakmt.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/libhsakmt.c
>   >> 53    /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/fmm.c:40:10: fatal error: numa.h: No such file or directory
>      54     #include <numa.h>
>      55              ^~~~~~~~
>      56    compilation terminated.
>   >> 57    make[2]: *** [CMakeFiles/hsakmt.dir/build.make:114: CMakeFiles/hsakmt.dir/src/fmm.c.o] Error 1
>      58    make[2]: *** Waiting for unfinished jobs....
>      59    make[2]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-build'
>   >> 60    make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/hsakmt.dir/all] Error 2
>      61    make[1]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-build'
>      62    make: *** [Makefile:153: all] Error 2
> 
> See build log for details:
>   /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-build-out.txt
> 
> ==> Error: Failed to install hsakmt-roct due to ChildError: ProcessError: Command exited with status 2:
>     'make' '-j4'
> 3 errors found in build log:
>      47    [ 18%] Building C object CMakeFiles/hsakmt.dir/src/fmm.c.o
>      48    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/fmm.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/fmm.c
>      49    [ 25%] Building C object CMakeFiles/hsakmt.dir/src/events.c.o
>      50    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/events.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/events.c
>      51    [ 31%] Building C object CMakeFiles/hsakmt.dir/src/libhsakmt.c.o
>      52    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/include -I/tmp/ruj
>            ak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wformat-security -Wswitch-default -Wundef -Wshadow -Wp
>            ointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-code -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFile
>            s/hsakmt.dir/src/libhsakmt.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/libhsakmt.c
>   >> 53    /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-src/src/fmm.c:40:10: fatal error: numa.h: No such file or directory
>      54     #include <numa.h>
>      55              ^~~~~~~~
>      56    compilation terminated.
>   >> 57    make[2]: *** [CMakeFiles/hsakmt.dir/build.make:114: CMakeFiles/hsakmt.dir/src/fmm.c.o] Error 1
>      58    make[2]: *** Waiting for unfinished jobs....
>      59    make[2]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-build'
>   >> 60    make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/hsakmt.dir/all] Error 2
>      61    make[1]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-kws7lnmqro65kc24sahbwkovnogpjji4/spack-build'
>      62    make: *** [Makefile:153: all] Error 2
> 
> 

</details>

**Comment by srekolam** [comment]
Can you install  numactl-libs-2.0.12-5.el7.x86_64 and  numactl-devel-2.0.12-5.el7.x86_64 . I think there is spack package for numactl which will provide the needed support similar to above but we have to verify and add it to hsakmt-roct package.

**Comment by SirRujak** [comment]
Thanks for the info, Solus doesn't have a native numactl package yet but I was able to make some progress by adding `depends_on('numactl@2.0.12', type='link')` to the hsakmt-roct spack definition. doing so gave the following errors:


<details>
  <summary>hsakmt-roct errors</summary>

  ```
  ==> hsakmt-roct: Executing phase: 'build'
  ==> Error: ProcessError: Command exited with status 2:
      'make' '-j4'

24 errors found in build log:
     49     [ 25%] Building C object CMakeFiles/hsakmt.dir/src/globals.c.o
     50     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/globals.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq6
            5/spack-src/src/globals.c
     51     [ 31%] Building C object CMakeFiles/hsakmt.dir/src/libhsakmt.c.o
     52     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/libhsakmt.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrs
            q65/spack-src/src/libhsakmt.c
     53     In file included from /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src/fmm.c:40:
     54     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'nodemask_equal':
  >> 55     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:110:16: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     56       tmp_a.maskp = (unsigned long *)a;
     57                     ^
  >> 58     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:113:16: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     59       tmp_b.maskp = (unsigned long *)b;
     60                     ^
     61     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'nodemask_equal_com
            pat':
  >> 62     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:123:16: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     63       tmp_a.maskp = (unsigned long *)a;
     64                     ^
  >> 65     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:126:16: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     66       tmp_b.maskp = (unsigned long *)b;
     67                     ^
     68     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: At top level:
  >> 69     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:255:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     70      int numa_num_possible_nodes();
     71      ^~~
  >> 72     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:258:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     73      int numa_num_possible_cpus();
     74      ^~~
  >> 75     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:261:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     76      int numa_num_configured_nodes();
     77      ^~~
  >> 78     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:264:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     79      int numa_num_configured_cpus();
     80      ^~~
  >> 81     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:267:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     82      int numa_num_task_cpus();
     83      ^~~
  >> 84     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:268:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     85      int numa_num_thread_cpus(); /* backward compatibility */
     86      ^~~
  >> 87     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:271:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     88      int numa_num_task_nodes();
     89      ^~~
  >> 90     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:272:1: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     91      int numa_num_thread_nodes(); /* backward compatibility */
     92      ^~~
  >> 93     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:275:8: error: function declarati
            on isn't a prototype [-Werror=strict-prototypes]
     94      struct bitmask *numa_allocate_cpumask();
     95             ^~~~~~~
  >> 96     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:344:26: error: function declarat
            ion isn't a prototype [-Werror=strict-prototypes]
     97      static inline nodemask_t numa_get_interleave_mask_compat()
     98                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  >> 99     /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:374:26: error: function declarat
            ion isn't a prototype [-Werror=strict-prototypes]
     100     static inline nodemask_t numa_get_membind_compat()
     101                              ^~~~~~~~~~~~~~~~~~~~~~~
     102    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'numa_alloc_interle
            aved_subset_compat':
  >> 103    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:390:14: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     104      tmp.maskp = (unsigned long *)mask;
     105                  ^
     106    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'numa_run_on_node_m
            ask_compat':
  >> 107    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:399:14: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     108      tmp.maskp = (unsigned long *)mask;
     109                  ^
     110    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: At top level:
  >> 111    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:404:26: error: function declarat
            ion isn't a prototype [-Werror=strict-prototypes]
     112     static inline nodemask_t numa_get_run_node_mask_compat()
     113                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     114    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'numa_interleave_me
            mory_compat':
  >> 115    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:420:14: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     116      tmp.maskp = (unsigned long *)mask;
     117                  ^
     118    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h: In function 'numa_tonodemask_me
            mory_compat':
  >> 119    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/opt/spack/linux-solus4-zen/gcc-8.3.0/numactl-2.0.12-5m4hsk7tmcpemtqnwbqliuryq4vi2jm7/include/numa.h:430:14: error: cast discards 'co
            nst' qualifier from pointer target type [-Werror=cast-qual]
     120      tmp.maskp = (unsigned long *)mask;
     121                  ^
     122    [ 37%] Building C object CMakeFiles/hsakmt.dir/src/memory.c.o
     123    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/memory.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65
            /spack-src/src/memory.c
     124    [ 43%] Building C object CMakeFiles/hsakmt.dir/src/openclose.c.o
     125    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/openclose.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrs
            q65/spack-src/src/openclose.c

     ...

     137    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/topology.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq
            65/spack-src/src/topology.c
     138    [ 87%] Building C object CMakeFiles/hsakmt.dir/src/rbtree.c.o
     139    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/rbtree.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65
            /spack-src/src/rbtree.c
     140    [ 93%] Building C object CMakeFiles/hsakmt.dir/src/version.c.o
     141    /mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/lib/spack/env/gcc/gcc  -Dhsakmt_EXPORTS -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spac
            k-src/include -I/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src  -O3 -DNDEBUG -fPIC   -fPIC -W -Wall -Wextra -Wno-unused-parameter -Wforma
            t-security -Wswitch-default -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wunreachable-c
            ode -std=gnu99 -fvisibility=hidden -Wlogical-op -Werror -O2 -o CMakeFiles/hsakmt.dir/src/version.c.o   -c /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq6
            5/spack-src/src/version.c
     142    /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src/topology.c: In function 'topology_parse_cpuinfo':
  >> 143    /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src/topology.c:884:5: error: 'strncpy' specified bound depends on the length of the source arg
            ument [-Werror=stringop-overflow=]
     144         strncpy(cpuinfo[proc].model_name, p, strlen(p) - 1);
     145         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     146    /tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-src/src/topology.c:882:8: note: length computed here
     147        if (strlen(p) < HSA_PUBLIC_NAME_SIZE) {
     148            ^~~~~~~~~
     149    cc1: all warnings being treated as errors
  >> 150    make[2]: *** [CMakeFiles/hsakmt.dir/build.make:114: CMakeFiles/hsakmt.dir/src/fmm.c.o] Error 1
     151    make[2]: *** Waiting for unfinished jobs....
     152    cc1: all warnings being treated as errors
  >> 153    make[2]: *** [CMakeFiles/hsakmt.dir/build.make:354: CMakeFiles/hsakmt.dir/src/topology.c.o] Error 1
     154    make[2]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-build'
  >> 155    make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/hsakmt.dir/all] Error 2
     156    make[1]: Leaving directory '/tmp/rujak/spack-stage/spack-stage-hsakmt-roct-3.5.0-jmxadouqcf4izqywcgxr2di7ftmrsq65/spack-build'
     157    make: *** [Makefile:153: all] Error 2

```

</details>

All of them appear to be warnings being treated as errors so just to see where I could get I eddited the -DHSAKMT_WERROR=1 to -DHSAKMT_WERROR=0 which allowed everything to build. There is one warning that `[OUTSIDE SOURCE PATH]: ../../rocclr_build/CMakeCache.txt` which appears to be due to the line referenced here: https://github.com/spack/spack/pull/17422#discussion_r462669267

When trying this on a fresh Solus install it appears to work with rocminfo and properly show the device so I am guessing that I was running into the problem of spack finding the wrong gcc before. After getting rocminfo working I ran into a build issue with pocl but that appears to be a separate issue so I am happy to close this issue unless you want to keep it open for the error on warnings. Thank you for the help!

**Comment by srekolam** [comment]
the current recipe in spack has the update to date changes. please refer to that ..this will be closed as resolved.
